spring:
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017  #27017
  cache: redis
  redis:
    host: localhost
    port: 6378 #6379
    timeOfLife: 60000
server:
  port: 8086